### PR TITLE
Restart backend daemons on store failure

### LINKED ISSUE #3347: Agent sessions are not terminated if backend cannot access etcd
## Expected Behavior
When the backend fails to contact etcd within a time window, its agent sessions are terminated.

## Current Behavior
Agent sessions can persist indefinitely. In some cases, it appears that agents can reconnect to other backends, and the old session will continue running on the backend in a zombie state. This has been observed by watching the prometheus metrics.

It is also possible that the metrics are not always decremented properly, this needs to be verified.

## Context
Issue observed while doing load and stability testing.

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

This change causes Sensu to shut down all of its internal backend daemons, and restart them, when an error from the store is marked as `ErrInternal`. These errors generally indicate that service has been lost, so Sensu should not keep trying to serve any requests. This will allow clients to select a different backend that may be working properly.

## Why is this change necessary?

It was discovered under load testing that clients would sometimes remain "stuck" on a server that had failed. In some cases the server never re-established itself as a member of the etcd cluster, leading to clients being connected but never working again, until the connection was severed and the client connected to a different backend.

Closes #3347 

## Refactoring

I refactored the pipelined daemon somewhat, moving the pipeline business logic to a new package, `pipeline`. I started doing this for eventd as well, but the task is more involved, and I wanted to timebox my efforts.

I would like to move all pipeline and event business logic outside of pipelined and eventd, with the expectation that this functionality will eventually be called directly by other parts of the system, like agentd and apid. However, while doing some exploratory work towards this, it quickly became apparent that this effort would expand the scope of this PR too much.

## Does your change need a Changelog entry?

Yes

## Have you reviewed and updated the documentation for this change? Is new documentation required?

This is a bugfix, no documentation changes are required.

## How did you verify this change?

I've smoke tested it on my laptop by starting up the system and executing checks, but I will need to test this on the performance cluster to verify that the failure mode works as we desire.

## Is this change a patch?

Yes

### CODE REVIEW

File: backend/agentd/agentd.go [hunk 1]
```diff
@@ -220,13 +220,17 @@ func (a *Agentd) webSocketHandler(w http.ResponseWriter, r *http.Request) {
 	if err != nil {
 		logger.WithError(err).Error("failed to create session")
 		http.Error(w, err.Error(), http.StatusInternalServerError)
+		// There was an error retrieving the namespace from
+		// etcd, indicating that this backend has a potentially
+		// unrecoverable issue.
+		a.errChan <- err
```
Comment (echlebek) [inline backend/agentd/agentd.go]: This error needs to be typechecked

File: backend/agentd/agentd.go [hunk 2]
```diff
@@ -220,13 +220,17 @@ func (a *Agentd) webSocketHandler(w http.ResponseWriter, r *http.Request) {
...
 		return
 	}
 
-	err = session.Start()
-	if err != nil {
+	if err := session.Start(); err != nil {
 		logger.WithError(err).Error("failed to start session")
 		http.Error(w, err.Error(), http.StatusInternalServerError)
+		a.errChan <- err
```
Comment (echlebek) [inline backend/agentd/agentd.go]: Ditto

File: backend/backend.go [hunk 3]
```diff
@@ -427,39 +443,33 @@ func (b *Backend) Run() error {
...
 
-	return derr
+	for {
+		if err := b.ctx.Err(); err != nil {
+			return nil
+		}
+		if err := b.runOnce(); err != nil {
+			logger.Error(err)
+		}
+	}
```
Comment (echlebek) [inline backend/backend.go]: This loop should be reworked to use the `retry` package.

File: backend/pipeline/handler.go [hunk 4]
```diff
@@ -67,13 +62,25 @@ func (p *Pipelined) handleEvent(event *types.Event) error {
 		handler := u.Handler
 		fields["handler"] = handler.Name
 
-		if filtered := p.filterEvent(handler, event); filtered {
+		filtered, err := p.filterEvent(handler, event)
+		if err != nil {
+			if _, ok := err.(*store.ErrInternal); ok {
```
Comment (golangcibot) [inline backend/pipeline/handler.go]: S1020: when ok is true, err can't be nil (from `gosimple`)

File: backend/store/etcd/extension_registry.go [hunk 5]
```diff
@@ -55,29 +51,34 @@ func (s *Store) RegisterExtension(ctx context.Context, ext *types.Extension) err
 // DeregisterExtension deregisters an extension
 func (s *Store) DeregisterExtension(ctx context.Context, name string) error {
 	if name == "" {
-		return errors.New("no extension name specified")
+		return &store.ErrNotValid{errors.New("no extension name specified")}
```
Comment (golangcibot) [inline backend/store/etcd/extension_registry.go]: composites: `github.com/sensu/sensu-go/backend/store.ErrNotValid` composite literal uses unkeyed fields (from `govet`)

**Comment by palourde** [comment]
@echlebek Were you able to successfully test the desired failure scenario? I'm trying to test that by running an external etcd that sensu-backend points to and that gets shutdown for ~1 minute but it never gets to the point where it restart all backend daemons. I have an agent connected with a standard check.

**Comment by palourde** [comment]
@echlebek I feel like there's something wrong going on. From a fresh install, I init sensu-backend and as soon as I connect an agent, the following appears on the backend logs:

```
{"level":"warn","ts":"2019-12-06T10:33:08.883-0500","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-29ab0911-481a-4f8f-8a91-f6de418f985c/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"component":"agentd","error":"internal error: context deadline exceeded","level":"error","msg":"failed to create session","time":"2019-12-06T10:33:08-05:00"}
{"component":"agentd","level":"warning","msg":"http: response.WriteHeader on hijacked connection from github.com/sensu/sensu-go/backend/agentd.(*Agentd).webSocketHandler (agentd.go:224)","time":"2019-12-06T10:33:08-05:00"}
{"component":"agentd","level":"warning","msg":"http: response.Write on hijacked connection from fmt.Fprintln (print.go:265)","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","error":"internal error: context deadline exceeded","level":"error","msg":"backend stopped working and is restarting","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down dashboardd","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down tessend","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down apid","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down keepalived","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down agentd","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down schedulerd","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down eventd","time":"2019-12-06T10:33:08-05:00"}
{"component":"eventd","level":"info","msg":"shutting down eventd","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down pipelined","time":"2019-12-06T10:33:08-05:00"}
{"component":"backend","level":"info","msg":"shutting down message_bus","time":"2019-12-06T10:33:08-05:00"}
```

**Comment by echlebek** [comment]
@palourde ah interesting. This doesn't occur without a fresh install. I'm investigating.

**Comment by echlebek** [comment]
@palourde hrm... I can't reproduce :/

File: backend/tessend/tessend.go [hunk 6]
```diff
@@ -553,7 +566,7 @@ func (t *Tessend) getPerResourceMetrics(now int64, data *Data) {
 		count, err := etcd.Count(t.ctx, t.client, metricFunc(t.ctx, ""))
 		if err != nil {
 			logger.WithError(err).Error("unable to retrieve resource count")
-			continue
+			return
```
Comment (nikkixdev) [inline backend/tessend/tessend.go]: Are we returning here because in the case of an error on `etcd.Count`, the backend will be restarted anyway?

File: backend/keepalived/deregisterer.go [hunk 7]
```diff
@@ -3,8 +3,9 @@ package keepalived
 import (
 	"context"
 	"fmt"
+	"time"
 
-	"github.com/sensu/sensu-go/api/core/v2"
+	v2 "github.com/sensu/sensu-go/api/core/v2"
```
[the remark this answers is not in the document]
Comment (echlebek) [reply backend/keepalived/deregisterer.go]: The fmt wants what it wants

File: backend/tessend/tessend.go (hunk 6 above)
Comment (echlebek) [reply backend/tessend/tessend.go]: Yes.

**Comment by nikkixdev** [comment]
Not sure if this is related to the changes in backend restart or otherwise, but it looks like a healthy backend in an unhealthy cluster (quorum lost) reports as unhealthy. Is this the expected behavior? Do you know if there were there any changes in the error reporting or contexts that could be attributed to this?
```
$ sensuctl cluster health
=== Etcd Cluster ID: cc009a6ac508317
         ID            Name                Error             Healthy  
 ────────────────── ─────────── ─────────────────────────── ───────── 
  8f778aef52e50525   backend-0   context deadline exceeded   false    
  d7cea4877c9a3137   backend-1   context deadline exceeded   false    
  e0ee8c7949a79049   backend-2   context deadline exceeded   false    
$ sensuctl cluster health
Error: GET "/health": Get https://127.0.0.1:8080/health?timeout=3: dial tcp 127.0.0.1:8080: connect: connection refused
$ sensuctl cluster health
Error: GET "/health": failed to request new refresh token; client returned 'Post https://127.0.0.1:8080/auth/token: dial tcp 127.0.0.1:8080: connect: connection refused'
```

**Comment by echlebek** [comment]
Cluster member health is defined as the ability to read a key from the store. When a majority of the cluster is unhealthy, then the store is unavailable. So there is no such thing as a healthy cluster member in an unhealthy cluster.

**Comment by nikkixdev** [comment]
Opened https://github.com/sensu/sensu-enterprise-go/pull/823 in response to this.
