### PR TITLE
Log statsd errors

### LINKED ISSUE #1473: Setting --statsd-metrics-host to an invalid address does not cause an error
When an invalid address is set, the agent starts up and does not report any error.

## Expected Behavior
The agent reports an error, or even crashes, when an invalid statsd listen address is specified.

## Current Behavior
The agent starts up and does not report an error.

## Steps to Reproduce (for bugs)
1. `./sensu-agent start --statsd-metrics-host 192.168.5.5`

### PR DESCRIPTION
**Pull request by nikkiki**
## What is this change?

Sensu-agent logs an error if the statsd listener is unable to start due to an invalid address or is stopped due to any other error.

## Why is this change necessary?

Closes #1473.

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Found https://github.com/sensu/sensu-go/issues/1498 and working on it next.

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -489,3 +477,50 @@ func (a *Agent) Stop() {
 func (a *Agent) addHandler(msgType string, handlerFunc handler.MessageHandlerFunc) {
 	a.handler.AddHandler(msgType, handlerFunc)
 }
+
+// StartStatsd starts up a StatsD listener on the agent, logs an error for any
+// failures.
+func (a *Agent) StartStatsd() {
```
Comment (echlebek) [inline agent/agent.go]: So I think this function is a bit more complex than it needs to be.

Consider:
```
var runStatsd func() error
if runtime.GOOS == "windows" {
    runStatsd = func() error {
        // windows specific stuff
    }
} else {
    runStatsd = func() error {
        // linux specific stuff
    }
}
if err := runStatsd(); err != nil {
    logger.WithError(err).Errorf("error running statsd on %s", addr)
}
```

There's also no need to handle errors with channels here, because the channels are not connecting different goroutines; the chan send and recv are in the same goroutine, so you can just use regular variable assignment and avoid the select.

Finally, keep in mind than an error can occur after a span of time has passed, it might not be from starting the server but another type of error. (Just for the sake of the error message being truthy)

Comment (nikkiki) [reply agent/agent.go]: @echlebek Yes, I did try to simplify this, but the caveat here is that `a.statsdServer.Run(a.context)` returns an error and must be run in a goroutine. From the research I did (ex. https://www.atatus.com/blog/goroutines-error-handling/) it seemed as though retrieving an error from a goroutine using channels was the safest way.

> Whether can we directly return values from goroutines similar to a normal function? This is a big no-no in the world of concurrency.

But if this is just referring to assigning variables between _different_ goroutines, then I can definitely go ahead and simplify this, since the two goroutines are _not_ connected in this case!

Comment (echlebek) [reply agent/agent.go]: Yeah, you definitely need to start up a new goroutine to handle this stuff, just don't need to use select mechanisms and channels here. :)

Comment (nikkiki) [reply agent/agent.go]: @echlebek it is done. 
giphy
