### PR TITLE
Audit and fix all etcd watchers

### LINKED ISSUE #2635: 100% CPU usage after a random period of time
## Expected Behavior

Sensu backend should run normally.

## Current Behavior

After a random period of time (can be lass than 2 hours or more than 12 hours), the sensu-backend process start to consume 100% of the CPU available on the virtual machines.

A restart of the process solves the problem until the next time. CPU is normally around 5% usage (there is only a few agents registered and only 3/4 checks per agents for now).

## Steps to Reproduce (for bugs)

This bug is totally random.

There is nothing abnormal in the logs. The backend still works as expected (scheduling checks, handling events, etc) but the sensu-backend process is taking 100% of the CPU.

## Context
Backend configuration:
```
# general configuration
state-dir: "/var/lib/sensu"

# etcd cluster configuration
etcd-advertise-client-urls: "http://sensu-etcd-cluster.staging.monitoring.xxx.com:2379"
no-embed-etcd: true

# deregistration
deregistration-handler: "deregister"

# logging
log-level: "debug"
```
## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.0
* Installation method (packages, binaries, docker etc.): Ubuntu packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

Backends are on AWS EC2 instances behind an ALB. etcd cluster is accessed through a NLB also on EC2 instances.

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

During a recent QA session, it was discovered that watchers could
fail permanently, but their consumers were using them as if they
could not. This was causing issues such as 100% CPU usage in some
components, and other components would simply fail to update until
service restart.

The problem mostly presents on backends that are using the
--no-embed-etcd mode, but can theoretically also occur on backends
that do embed etcd.

All watchers now get reinstated on a retry loop when they fail, and
all watchers now require that a leader is present, so that watchers
do not get stuck on partitions.

## Why is this change necessary?

Closes #2635 

## Does your change need a Changelog entry?

Added

## How did you verify this change?

This change is still unverified beyond automated testing, and needs to be put through a full QA cycle.

### CODE REVIEW

**Comment by palourde** [comment]
@echlebek Quick note, the watcher wrapper was already used by sensu-enterprise-go so once this PR is merged, it will probably require a patch too!

File: backend/store/etcd/watchers.go [hunk 1]
```diff
@@ -130,37 +112,34 @@ func (s *Store) GetEntityWatcher(ctx context.Context) <-chan store.WatchEventEnt
 // restart the watcher, if needed.
```
Comment (nikkiki) [inline backend/store/etcd/watchers.go]:
```suggestion
// The watcher does its best to recover from errors.
```

File: backend/store/etcd/watchers.go [hunk 2]
```diff
@@ -130,37 +112,34 @@ func (s *Store) GetEntityWatcher(ctx context.Context) <-chan store.WatchEventEnt
...
+			var tessen corev2.TessenConfig
 
-				watchEvent := store.WatchEventTessenConfig{
-					Action:       action,
-					TessenConfig: tessen,
+			if response.Type == store.WatchDelete {
+				tessen = *corev2.DefaultTessenConfig()
+			} else {
+				if err := json.Unmarshal(response.Object, &tessen); err != nil {
+					logger.WithField("key", response.Key).WithError(err).Error("unable to unmarshal check config from key")
```
Comment (nikkiki) [inline backend/store/etcd/watchers.go]:
```suggestion
					logger.WithField("key", response.Key).WithError(err).Error("unable to unmarshal tessen config from key")
```

File: backend/store/etcd/watchers.go [hunk 3]
```diff
@@ -81,46 +68,41 @@ func (s *Store) GetCheckConfigWatcher(ctx context.Context) <-chan store.WatchEve
...
-				watchEvent := store.WatchEventEntity{
-					Action: action,
-					Entity: &entity,
+			if response.Type == store.WatchDelete {
+				meta := store.ParseResourceKey(response.Key)
+				entity.Namespace = meta.Namespace
+				entity.Name = meta.ResourceName
+			} else {
+				if err := json.Unmarshal(response.Object, &entity); err != nil {
+					logger.WithField("key", response.Key).WithError(err).Error("unable to unmarshal check config from key")
```
Comment (nikkiki) [inline backend/store/etcd/watchers.go]:
```suggestion
					logger.WithField("key", response.Key).WithError(err).Error("unable to unmarshal entity from key")
```

File: backend/liveness/liveness.go [hunk 4]
```diff
@@ -245,15 +246,23 @@ func (t *SwitchSet) monitor(ctx context.Context) {
 		}
 	}()
 	go func() {
+		var wc clientv3.WatchChan
+		ctx := clientv3.WithRequireLeader(ctx)
+		limiter := rate.NewLimiter(rate.Every(time.Second), 1)
+		_ = limiter.Wait(ctx)
+	OUTER:
+		wc = t.client.Watch(ctx, t.prefix, clientv3.WithPrefix(), clientv3.WithPrevKV())
```
Comment (palourde) [inline backend/liveness/liveness.go]: Stupid question: do we need to move the rate limiter `Wait` method within the `OUTER` label? Maybe I'm misreading it because what I understand is that it would only be rate limiting once the goroutine starts.

Comment (echlebek) [reply backend/liveness/liveness.go]: Ah good question. The intent of the limiter is that no more than one `Watch` request will be made per second. That is, if the system tries to create a `Watch` over and over again, but fails consistently, it will not do so faster than once per second.

File: backend/store/etcd/watchers.go [hunk 5]
```diff
@@ -81,86 +68,78 @@ func (s *Store) GetCheckConfigWatcher(ctx context.Context) <-chan store.WatchEve
...
 			}
 		}
 	}()
+
 	return ch
 }
 
 // GetTessenConfigWatcher returns a channel that emits WatchEventTessenConfig structs notifying
 // the caller that a TessenConfig was updated. If the watcher runs into a terminal error
 // or the context passed is cancelled, then the channel will be closed. The caller must
```
Comment (nikkiki) [inline backend/store/etcd/watchers.go]: I wish you could do multi-line suggestions

```suggestion
// or the context passed is cancelled, then the channel will be closed.
```

Comment (echlebek) [reply backend/store/etcd/watchers.go]: Thanks, I'll look into it
