### PR TITLE
[CLI] Do not swallow errors in list package

### LINKED ISSUE #1147: [CLI] list package should not swallow errors
Originally brought up in: https://github.com/sensu/sensu-go/pull/1141#discussion_r173318441.

CLI's `list` package should return errors when:

- a transform fails
- or, if it is unable to write to given io.Writer.

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

No longer swallow errors that occur in `list` package.

## Why is this change necessary?

Closes #1147 
Originally brought up in: #1141 (comment).

### CODE REVIEW

**Comment by grepory** [comment]
This is causing e2e tests to fail

```
--- FAIL: TestKeepaliveTimeout (14.12s)
	Error Trace:	keepalive_test.go:204
	Error:      	Received unexpected error:
	            	invalid character '=' after top-level value
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8c52f0]
goroutine 83 [running]:
testing.tRunner.func1(0xc4201ae780)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:742 +0x29d
panic(0x961460, 0xd401f0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
github.com/sensu/sensu-go/testing/e2e.TestKeepaliveTimeout(0xc4201ae780)
	/home/travis/gopath/src/github.com/sensu/sensu-go/testing/e2e/keepalive_test.go:207 +0x430
testing.tRunner(0xc4201ae780, 0xa25110)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:824 +0x2e0
FAIL	github.com/sensu/sensu-go/testing/e2e	62.595s
```

**Comment by grepory** [comment]
This causes sensuctl to print output in both the preferred output format and the `none`? output format.

E.g.:

```
λ bin/sensuctl event info agent1 keepalive
{
  "timestamp": 1521069336,
  "entity": {
    "class": "agent",
    "deregister": false,
    "deregistration": {},
    "environment": "default",
    "id": "agent1",
    "keepalive_timeout": 120,
    "last_seen": 1521067289,
    "organization": "default",
    "redact": [
      "password",
      "passwd",
      "pass",
      "api_key",
      "api_token",
      "access_key",
      "secret_key",
      "private_key",
      "secret"
    ],
    "subscriptions": [
      "test",
      "entity:agent1"
    ],
    "system": {
      "hostname": "agent1",
      "os": "linux",
      "platform": "alpine",
      "platform_family": "alpine",
      "platform_version": "3.6.2",
      "network": {
        "interfaces": [
          {
            "name": "lo",
            "addresses": [
              "127.0.0.1/8"
            ]
          },
          {
            "name": "tunl0",
            "addresses": null
          },
          {
            "name": "ip6tnl0",
            "addresses": null
          },
          {
            "name": "eth0",
            "mac": "02:42:ac:12:00:02",
            "addresses": [
              "172.18.0.2/16"
            ]
          }
        ]
      }
    },
    "user": "agent"
  },
  "check": {
    "check_hooks": null,
    "duration": 0,
    "environment": "default",
    "handlers": [
      "keepalive"
    ],
    "high_flap_threshold": 0,
    "history": [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {}
    ],
    "interval": 120,
    "low_flap_threshold": 0,
    "name": "keepalive",
    "organization": "default",
    "proxy_entity_id": "",
    "publish": false,
    "round_robin": false,
    "runtime_assets": null,
    "state": "failing",
    "status": 1,
    "stdin": false,
    "subdue": null,
    "subscriptions": null,
    "timeout": 0,
    "total_state_change": 0
  }
}

=== agent1 - keepalive
Entity:    agent1
Check:     keepalive
Output:
Status:    1
History:   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Silenced:  false
Timestamp: 2018-03-14 16:15:36 -0700 PDT
```

This happens for other info commands as well.

File: cli/commands/entity/info.go [hunk 1]
```diff
@@ -43,11 +43,8 @@ func ShowCommand(cli *cli.SensuCli) *cobra.Command {
 				if err := helpers.PrintJSON(r, cmd.OutOrStdout()); err != nil {
 					return err
 				}
-			} else {
```
Comment (grepory) [inline cli/commands/entity/info.go]: The removal of all of these elses from InfoCommands is what's causing this behavior.
