### PR TITLE
Checks should not duplicately execute after its proxy requests have executed

### LINKED ISSUE #1054: Investigate TestProxyChecks intermittent failure
```
--- FAIL: TestProxyChecks (22.20s)
	assertions.go:239: 
                          
	Error Trace:	proxy_checks_test.go:99
		
	Error:      	An error is expected but got nil.
		
	Messages:   	{
		
	            	  "timestamp": 1519231750,
		
	            	  "entity": {
		
	            	    "class": "agent",
		
	            	    "deregister": false,
		
	            	    "deregistration": {},
		
	            	    "environment": "default",
		
	            	    "id": "TestProxyChecks",
		
	            	    "keepalive_timeout": 10,
		
	            	    "organization": "default",
		
	            	    "redact": [
		
	            	      "password",
		
	            	      "passwd",
		
	            	      "pass",
		
	            	      "api_key",
		
	            	      "api_token",
		
	            	      "access_key",
		
	            	      "secret_key",
		
	            	      "private_key",
		
	            	      "secret"
		
	            	    ],
		
	            	    "subscriptions": [
		
	            	      "test",
		
	            	      "entity:TestProxyChecks"
		
	            	    ],
		
	            	    "system": {
		
	            	      "hostname": "travis-job-4a935945-eee3-40f3-aeaa-00b876b5fafe",
		
	            	      "os": "linux",
		
	            	      "platform": "ubuntu",
		
	            	      "platform_family": "debian",
		
	            	      "platform_version": "14.04",
		
	            	      "network": {
		
	            	        "interfaces": [
		
	            	          {
		
	            	            "name": "lo",
		
	            	            "addresses": [
		
	            	              "127.0.0.1/8"
		
	            	            ]
		
	            	          },
		
	            	          {
		
	            	            "name": "eth0",
		
	            	            "mac": "42:01:0a:14:01:cc",
		
	            	            "addresses": [
		
	            	              "10.20.1.204/32"
		
	            	            ]
		
	            	          },
		
	            	          {
		
	            	            "name": "docker0",
		
	            	            "mac": "02:42:97:1e:53:63",
		
	            	            "addresses": [
		
	            	              "172.17.0.1/16"
		
	            	            ]
		
	            	          }
		
	            	        ]
		
	            	      },
		
	            	      "arch": "amd64"
		
	            	    },
		
	            	    "user": "agent"
		
	            	  },
		
	            	  "check": {
		
	            	    "check_hooks": null,
		
	            	    "command": "command",
		
	            	    "duration": 0.000868417,
		
	            	    "environment": "default",
		
	            	    "executed": 1519231750,
		
	            	    "handlers": [],
		
	            	    "high_flap_threshold": 0,
		
	            	    "history": null,
		
	            	    "interval": 1,
		
	            	    "low_flap_threshold": 0,
		
	            	    "name": "check_proxy",
		
	            	    "organization": "default",
		
	            	    "proxy_entity_id": "",
		
	            	    "proxy_requests": {
		
	            	      "entity_attributes": [
		
	            	        "entity.Class == \"proxy\""
		
	            	      ]
		
	            	    },
		
	            	    "publish": true,
		
	            	    "round_robin": false,
		
	            	    "runtime_assets": [
		
	            	      "ruby-2-4-2"
		
	            	    ],
		
	            	    "state": "passing",
		
	            	    "stdin": false,
		
	            	    "subdue": null,
		
	            	    "subscriptions": [
		
	            	      "test"
		
	            	    ],
		
	            	    "timeout": 0,
		
	            	    "total_state_change": 0
		
	            	  }
		
	            	}
```

### PR DESCRIPTION
**Pull request by nikkiattea**
Signed-off-by: Nikki Attea <nikki@sensu.io>

## What is this change?

Resolves a bug in how an executor processes checks. If a check contains proxy requests, the check should not duplicately execute after the proxy requests.

## Why is this change necessary?

Closes #1054.

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Copying and pasting code is deadly.. glad this is resolved and interfaced! Also, this is another intermittent failure which after this change did not reproduce on 200 attempts under medium load locally.

### CODE REVIEW

File: backend/schedulerd/executor.go [hunk 1]
```diff
@@ -281,10 +281,12 @@ func processCheck(ctx context.Context, executor Executor, check *types.CheckConf
...
-				logger.Info("no matching entities, check will not be published")
 			}
+		} else {
+			logger.Info("no matching entities, check will not be published")
 		}
+	} else {
+		return executor.execute(check)
 	}
-	return executor.execute(check)
+	return nil
```
Comment (mercul3s) [inline backend/schedulerd/executor.go]: Ah this change makes total sense. We definitely shouldn't be executing a check if we've already submitted it for proxy checks!

**Comment by mercul3s** [comment]
everybody-loves-raymond-doris-roberts-marie-barone-FmMaRXfuLVi8w

File: backend/schedulerd/executor.go (hunk 1 above)
Comment (nikkiattea) [reply backend/schedulerd/executor.go]: I didn't catch it when I refactored either! But we're all good now 😄
