### PR TITLE
Terminate processes gracefully in e2e tests

### LINKED ISSUE #1228: TestAgentReconnection intermittently fails
The TestAgentReconnection test is intermittently failing in CI.

## Expected Behavior
Test should pass.

## Current Behavior
Seeing the following:

```
--- FAIL: TestAgentReconnection (22.14s)
	Error Trace:	agent_reconnection_test.go:57
	Error:      	Received unexpected error:
	            	exit status 1
	Messages:   	Error: Get http://127.0.0.1:42638/events/TestAgentReconnection/keepalive?env=default&org=default: dial tcp 127.0.0.1:42638: connect: connection refused
	Error Trace:	agent_reconnection_test.go:60
	Error:      	Received unexpected error:
	            	invalid character 'E' looking for beginning of value
```

https://travis-ci.org/sensu/sensu-go/jobs/358521947#L1868

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Failure is intermittent so it may be tough to reproduce.

## Context
N/A

## Your Environment
Travis CI

### PR DESCRIPTION
**Pull request by cyphus**
## What is this change?

Terminate processes gracefully in e2e tests, allowing ports to be reused.

## Why is this change necessary?

Fixes #1228 

## Does your change need a Changelog entry?

Yes:

### Fixes
- Terminate processes gracefully in e2e tests, allowing ports to be reused.

## Do you need clarification on anything?

I need clarification on the hardest part: naming things. If there is a name or place for `terminate_helper` that would fit project conventions better, I'd love to hear about it.

## Were there any complications while making this change?

I spent some time trying to find a way to gracefully terminate CLI processes on Windows -- sadly there is no supported way to do this in Windows.

### CODE REVIEW

File: testing/e2e/process_test.go [hunk 1]
```diff
@@ -355,3 +351,21 @@ func (s *sensuCtl) run(args ...string) ([]byte, error) {
 func (s *sensuCtl) SetStdin(r io.Reader) {
 	s.stdin = r
 }
+
+// Terminate a Process by sending SIGTERM and waiting for it to exit cleanly.
+// On Windows, there is no way to ask a program to exit cleanly. Instead, it
+// must be killed with SIGKILL.
+func terminate_helper(p *os.Process) error {
```
Comment (mercul3s) [inline testing/e2e/process_test.go]: I'd suggest using came case here per Go convention: `terminateHelper`; could also be named `terminateProcess`. Otherwise, I think this is the right place for this function to go 👍

Comment (echlebek) [reply testing/e2e/process_test.go]: +1 to `terminateProcess`

Comment (cyphus) [reply testing/e2e/process_test.go]: Ah of course! I was so focused on the `helper` part of the name that I completely missed the fact that I was using snake case 🤦‍♂️ `terminateProcess` sounds good, I'll update.
