### PR TITLE
Logrus logging should accept field arguments

### LINKED ISSUE #1199: Logrus logging should accept field arguments
From our [Logrus](https://github.com/sirupsen/logrus) dependency:
>Logrus encourages careful, structured logging through logging fields instead of long, unparseable error messages. For example, instead of: `log.Fatalf("Failed to send event %s to topic %s with key %d")`, you should log the much more discoverable:

```
log.WithFields(log.Fields{
  "event": event,
  "topic": topic,
  "key": key,
}).Fatal("Failed to send event")
```

## Expected Behavior
By using logrus fields properly, we will get a more readable log message:
`{"component":"agentd","level":"warning","msg":"stopping session","recv error":"Connection closed: websocket: close 1001 (going away): bye","session":"01bad4b2-bec4-454b-a72e-10a4e106445f","time":"2018-03-21T10:21:54-05:00"}`

## Current Behavior
By using our current logging behavior, we get an unparseable log message:
`{"component":"agentd","level":"warning","msg":"stopping session \u003c%s\u003e: recv error: 01bad4b2-bec4-454b-a72e-10a4e106445fConnection closed: websocket: close 1001 (going away): bye","time":"2018-03-21T10:21:54-05:00"}`

## Possible Solution
Use logrus.Fields in place of variable formatting _everywhere_ we log.

### PR DESCRIPTION
**Pull request by nikkiattea**
Signed-off-by: Nikki Attea <nikki@sensu.io>

## What is this change?

Updates and corrects logging style for variable fields (uses WithFields and WithError when applicable).

## Why is this change necessary?

Closes #1199.

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Nah.

### CODE REVIEW

File: backend/apid/middlewares/refresh_token.go [hunk 1]
```diff
@@ -46,42 +47,41 @@ func (m RefreshToken) Then(next http.Handler) http.Handler {
...
 		if accessClaims.Subject == "" || accessClaims.Subject != refreshClaims.Subject {
-			logger.WithField(
-				"user", refreshClaims.Subject,
-			).Errorf("the access and refresh tokens subject do not match: %s != %s",
-				accessClaims.Subject,
-				refreshClaims.Subject,
-			)
+			logger.WithFields(logrus.Fields{
+				"user":            refreshClaims.Subject,
+				"token (access)":  accessClaims.Subject,
```
Comment (grepory) [inline backend/apid/middlewares/refresh_token.go]: fields are typically searched for, it'd be best if they didn't include characters like spaces or parens. Can we make things like this access_token and refresh_token?

File: backend/backend.go [hunk 2]
```diff
@@ -381,8 +382,10 @@ func (b *Backend) Run() (derr error) {
 	defer func() {
 		if err := recover(); err != nil {
 			trace := string(debug.Stack())
-			logger.Errorf("panic in %s", trace)
-			logger.Errorf("recovering from panic due to error %s, shutting down etcd", err)
+			logger.WithFields(logrus.Fields{
+				"error": err,
```
Comment (grepory) [inline backend/backend.go]: WithError instead of error field.

File: backend/agentd/session.go [hunk 3]
```diff
@@ -212,7 +219,7 @@ func (s *Session) Start() (err error) {
 
 	for _, sub := range s.cfg.Subscriptions {
 		topic := messaging.SubscriptionTopic(org, env, sub)
-		logger.Debugf("Subscribing to topic %q", topic)
+		logger.WithField("topic", topic).Debug("Subscribing to topic")
```
Comment (grepory) [inline backend/agentd/session.go]: for the sake of consistency, can we change the capitalization of Subscribing to subscribing?
