### PR TITLE
Bugfix/agent panic

### LINKED ISSUE #3779: executeCheck() gets SIGSEGV when command in hook is invalid, and the agent reports nothing
## Expected Behavior

even when configuration is invalid, the agent should not killed by SIGSERV, and should reports the problem.

## Current Behavior

when `command` in hook is invalid, the agent gets SIGSEGV. and the problem is not reported back to user. the status of the check remains `success`.

```
May 21 17:36:23  sensu_agent[2773]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 17:36:23  sensu_agent[2773]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xe5e0dc]
May 21 17:36:23  sensu_agent[2773]: 
May 21 17:36:23  sensu_agent[2773]: goroutine 87 [running]:
May 21 17:36:23  sensu_agent[2773]: github.com/sensu/sensu-go/agent.(*Agent).ExecuteHooks(0xc0001b6dc0, 0x128b0a0, 0xc00015c540, 0xc0005fc080, 0xc0000f8a80, 0x0, 0x6, 0x8, 0x0)
May 21 17:36:23  sensu_agent[2773]:     /wrkdirs/usr/ports/sysutils/sensu-go-agent/work/sensu-go-5.20.0/agent/hook.go:30 +0x26c
May 21 17:36:23  sensu_agent[2773]: github.com/sensu/sensu-go/agent.(*Agent).executeCheck(0xc0001b6dc0, 0x128b0a0, 0xc00015c540, 0xc0005fc080, 0xc000256000)
May 21 17:36:23  sensu_agent[2773]:     /wrkdirs/usr/ports/sysutils/sensu-go-agent/work/sensu-go-5.20.0/agent/check_handler.go:252 +0xe8f
May 21 17:36:23  sensu_agent[2773]: created by github.com/sensu/sensu-go/agent.(*Agent).handleCheck
May 21 17:36:23  sensu_agent[2773]:     /wrkdirs/usr/ports/sysutils/sensu-go-agent/work/sensu-go-5.20.0/agent/check_handler.go:69 +0x2c8
```

the end result is that, after the hook execution error, the check reports nothing. and the web ui says nothing about the problem.

## Possible Solution

whenever child process is killed, the agent should report the problem.

## Steps to Reproduce (for bugs)

1. create a hook with command including shell pipe, like this:

```yaml
type: HookConfig
api_version: core/v2
metadata:
  created_by: admin
  name: dmesg
  namespace: default
spec:
  command: dmesg | tail
  runtime_assets: null
  stdin: false
  timeout: 10
```

2. attach the hook to a check

## Context

fixing "nil pointer dereference" that caused SIGSEGV is one thing, but the agent should have not been fragile like this.

I would argue that using pipe is one of common operations for which the hook is designed. but that would be reserved for another bug report.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.20.0
* Installation method (packages, binaries, docker etc.): my own build
* Operating System and version (e.g. Ubuntu 14.04): FreeBSD 12.1

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

```
    Fix a nil panic in sensu-agent
    
    This commit fixes a nil panic in sensu-agent when a hook is
    specified that does not exist. Additionally, other hook config
    errors are now surfaced properly instead of via an out-of-band
    event.
```

## Why is this change necessary?

Fixes #3779 

## Does your change need a Changelog entry?

Yes

## Do you need clarification on anything?

No

## Were there any complications while making this change?

The agent hook failure protocol required some review.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

Documentation changes are not required.

## How did you verify this change?

The unit test in the first commit of this changelog proves that the fix works.

## Is this change a patch?

Yes

### CODE REVIEW

File: agent/hook.go [hunk 1]
```diff
@@ -50,6 +51,19 @@ func (a *Agent) ExecuteHooks(ctx context.Context, request *corev2.CheckRequest,
...
 
+// errorHookConfig will return a hookConfig that will echo its error argument
+// and exit status 2.
+func errorHookConfig(namespace, name string, err error) *corev2.HookConfig {
+	return &corev2.HookConfig{
+		ObjectMeta: corev2.ObjectMeta{
+			Namespace: namespace,
+			Name:      name,
+		},
+		Command: fmt.Sprintf("echo 'hook %s: %s'; exit 2", name, err),
```
Comment (palourde) [inline agent/hook.go:62]: The resulting command was a bit confusing to me in my tests, e.g.
```
hooks:
    - command: 'echo ''hook prout: missing hook config''; exit 2'
```

Is this the intended behaviour?

Comment (echlebek) [reply agent/hook.go:62]: That looks like yaml serialization weirdness to me. I'm not sure if it's a problem or not...

Comment (echlebek) [reply agent/hook.go:62]: According to the yaml specification, two single quotes are how single quotes are escaped in yaml. https://yaml.org/spec/current.html#id2534365
