### PR TITLE
Fix bug in topic done chan closed on subscribe

### LINKED ISSUE #1407: Agent check execution appears to miss some checks on a tight interval
Recently, testing has revealed that on tight intervals, such as 1 second, agents can "miss" check executions, even when the check executed is very short.

I suspect that there may be some inefficiency or blocking call in the agent code that executes the check, that is triggering the 'check execution still in progress' error to occur.

Verify if the error is really occurring, and if it is, determine why and fix the problem.

### PR DESCRIPTION
**Pull request by mercul3s**
## What is this change?

Fixes an issue in which agents re-connecting may experience missed or skipped check requests.

## Why is this change necessary?

Closes #1407 

## Does your change need a Changelog entry?

Added under `Fixed`.

## Do you need clarification on anything?

Nope!

## Were there any complications while making this change?

This was a really gnarly bug that took the debugging efforts of myself, @cyphus, and @echlebek to deduce.

### CODE REVIEW

File: backend/messaging/wizard_bus.go [hunk 1]
```diff
@@ -116,11 +116,18 @@ func (b *WizardBus) Subscribe(topic string, consumer string, sub Subscriber) (Su
 	b.topicsMu.Lock()
 	defer b.topicsMu.Unlock()
 
-	if _, ok := b.topics[topic]; !ok {
-		b.topics[topic] = b.createTopic(topic)
+	t, ok := b.topics[topic]
+	if !ok {
```
Comment (echlebek) [inline backend/messaging/wizard_bus.go]: just noticed we can refactor a bit here:
```
t, ok := b.topics[topic]
if !ok || t.IsClosed() {
    t = b.createTopic(topic)
    b.topics[topic] = t
}
```

Comment (mercul3s) [reply backend/messaging/wizard_bus.go]: Oh, that cleans up nicely 👍
