### PR TITLE
Handle case where refresh token is no longer in allow list

### LINKED ISSUE #2462: When a disabled user attempts to use their refresh token they receive an err
## Expected Behavior

Receive a `401` status code when attempting to use refresh token to new auth tokens. 

## Current Behavior

```js
// client attempts to query but receives 401 because access token is no longer valid
{"access token":"3a4565a348e6af3aed990e70ba4a7f6a","component":"apid","error":"token 3a4565a348e6af3aed990e70ba4a7f6a for viewer does not exist","level":"error","msg":"access token is not authorized","time":"2018-11-29T02:30:01Z","user":"viewer"}
{"component":"apid","duration":"3.384ms","level":"info","method":"POST","msg":"request completed","path":"/graphql","size":21,"status":401,"time":"2018-11-29T02:30:01Z"}

// client attempts to refresh but receives 500
{"component":"apid.routers","level":"error","msg":"the refresh token is not authorized: token 66bd0d29b775a6af620f12d34a53ec4c for viewer does not exist","time":"2018-11-29T02:30:01Z","user":"viewer"}
{"component":"apid","duration":"2.236ms","level":"info","method":"POST","msg":"request completed","path":"/auth/token","size":102,"status":500,"time":"2018-11-29T02:30:01Z"}
```

## Possible Solution

When refreshing handle case where the refresh token is no longer in the allow list.

## Steps to Reproduce (for bugs)

```
sensuctl user create fren --password idkidkidkidkwhynot

# sign into the web app with the new user
# navigate around

sensuctl user disable fren

# in the web app you should see an unhandled exception
# congrats you are stuck until you wipe localStorage
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.0.0
* Installation method (packages, binaries, docker etc.): docker
* Operating System and version (e.g. Ubuntu 14.04): macOS

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

Handles case where a refresh token is no longer in the allow list and a user attempts to use the refresh token.

**Example 1:**

1. User A has configured `sensuctl`.
1. User B disables User A's account.
1. User A attempts to list events.
1. User A receives a nondescript internal error.

**Example 2:**

1. User A is signed into the web app.
1. User B disabled User A's account.
1. User A is presented with a dialog, communicating that their session is no longer valid.
1. User A can re-authenticate if and when their account is reinstated.

## Why is this change necessary?

Closes #2462 

## Does your change need a Changelog entry?

Probably.

### CODE REVIEW

File: backend/apid/middlewares/allowlist_test.go [hunk 1]
```diff
@@ -57,7 +59,7 @@ func TestMissingTokenFromAllowList(t *testing.T) {
 	// Perform the request with the middleware
 	res, err := http.DefaultClient.Do(req)
 	assert.NoError(t, err)
-	assert.Equal(t, http.StatusUnauthorized, res.StatusCode)
+	assert.Equal(t, res.StatusCode, http.StatusUnauthorized)
```
Comment (nikkiki) [inline backend/apid/middlewares/allowlist_test.go]: The documentation appears that the order is expected, then actual: https://godoc.org/github.com/stretchr/testify/assert#Equal
```suggestion
	assert.Equal(t, http.StatusUnauthorized, res.StatusCode)
```

Comment (jamesdphillips) [reply backend/apid/middlewares/allowlist_test.go]: 🤦‍♂️
