### PR TITLE
Fix a bug in keepalived that could result in a crash

### LINKED ISSUE #2638: Sensu-go 5.1.1 backend is crashing
## Expected Behavior

I'd expect sensu-puppet tests that passed with 5.1.0 to pass with 5.1.1.

## Current Behavior

Currently several tests are failing here: https://travis-ci.org/sensu/sensu-puppet/jobs/484138033

I see things like this:

```
 Error: Failed to apply catalog: Execution of '/usr/bin/sensuctl mutator list --all-namespaces --format json' returned 1: Error: Get https://sensu_backend:8080/api/core/v2/mutators: dial tcp 172.17.0.3:8080: connect: connection refused
```

Then later `sensuctl` commands are successful even though the service was not restarted.  My hunch is that sensu-backend is crashing and systemd is automatically restarting the daemon.

## Steps to Reproduce (for bugs)

I am not sure yet.

## Context

I am working with @ghoneycutt on sensu-puppet module and acceptance tests are failing with latest 5.1.1 release and did not fail with 5.1.0.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.1
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

This commit fixes a case in keepalived where the backend could
crash if the system was unable to find an event it expected to be
able to find. Now, if the backend is unable to find the event, an
error is logged and the keepalive processing terminates early.

## Why is this change necessary?

Closes #2638 

## Does this change require a new test case?

Added a unit test and also a testrails QA test.

## Additional information
I made sure the same problem did not exist in eventd for check TTL.

### CODE REVIEW

File: backend/keepalived/keepalived_test.go [hunk 1]
```diff
@@ -272,3 +273,54 @@ func TestCreateKeepaliveEvent(t *testing.T) {
 	assert.Equal(t, uint32(20), keepaliveEvent.Check.Interval)
 	assert.Equal(t, uint32(120), keepaliveEvent.Check.Timeout)
 }
+
+func TestDeadCallbackNoEntity(t *testing.T) {
+	// Make sure the dead callback doesn't crash when entity is missing
+	messageBus, err := messaging.NewWizardBus(messaging.WizardBusConfig{
```
Comment (golangcibot) [inline backend/keepalived/keepalived_test.go]: ineffectual assignment to `err` (from `ineffassign`)

File: backend/keepalived/keepalived_test.go [hunk 2]
```diff
@@ -272,3 +273,54 @@ func TestCreateKeepaliveEvent(t *testing.T) {
...
+	}
+	store.On("GetEntityByName", mock.Anything, mock.Anything).Return((*corev2.Entity)(nil), nil)
+
+	// Smoke test - just want to make sure there is no panic
+	keepalived.dead("default/testSubscriber", liveness.Alive, true)
+}
+
+func TestDeadCallbackNoEvent(t *testing.T) {
+	// Make sure the dead callback doesn't crash when entity is missing
+	messageBus, err := messaging.NewWizardBus(messaging.WizardBusConfig{
```
Comment (golangcibot) [inline backend/keepalived/keepalived_test.go]: ineffectual assignment to `err` (from `ineffassign`)
