### PR TITLE
API URL

### LINKED ISSUE #2461: Dashboard is broken in the presence of TLS
When the dashboard is configured to use TLS, hostname verification fails, rendering it unusable.

From @palourde:

https://github.com/sensu/sensu-go/blob/f8b13b06b8783821918878b5b91293515e091d71/backend/apid/apid.go#L96. We pass “url”, which is defined at line https://github.com/sensu/sensu-go/blob/f8b13b06b8783821918878b5b91293515e091d71/backend/apid/apid.go#L88. It uses the “listen” host IP

Suggested solution:
We probably just need to make a distinction between the address APId listens on and the advertised one, just like etcd does

### PR DESCRIPTION
**Pull request by palourde**
Signed-off-by: Simon Plourde <simon@sensu.io>

## What is this change?

It adds a new configuration attribute in the backend for specifying the API URL the dashboard will use.

## Why is this change necessary?

Closes https://github.com/sensu/sensu-go/issues/2461

## Does your change need a Changelog entry?

Added

## Do you need clarification on anything?

Nope

## Were there any complications while making this change?

Naming things

## Have you reviewed and updated the documentation for this change? Is new documentation required?

Already done

Closes #2461

### CODE REVIEW

File: backend/dashboardd/dashboardd.go [hunk 1]
```diff
@@ -221,8 +220,6 @@ func newBackendProxy(host string, port int, TLS *types.TLSOptions) (*httputil.Re
 
 	// Configure TLS
 	if TLS != nil {
-		target.Scheme = "https"
-
```
Comment (jamesdphillips) [inline backend/dashboardd/dashboardd.go]: I wonder if we can remove `cfg.InsecureSkipVerify = true` from L227 now? I think this is an artifact from when the dashboard statically defined `localhost` as the APIUrl.

https://github.com/sensu/sensu-go/blob/add72d2f5c001c67ff94ce440b3d642a479795dc/backend/dashboardd/dashboardd.go#L227

Comment (palourde) [reply backend/dashboardd/dashboardd.go]: We are now using it EVERYWHERE instead 🤣

Comment (jamesdphillips) [reply backend/dashboardd/dashboardd.go]: not sure if I want to laugh or cry

File: backend/apid/apid.go [hunk 2]
```diff
@@ -78,27 +70,23 @@ func New(c Config, opts ...Option) (*APId, error) {
 	var tlsConfig *tls.Config
 	var err error
 	if c.TLS != nil {
+		// TODO(palourde): We should avoid using the loopback interface
+		c.TLS.InsecureSkipVerify = true
```
Comment (jamesdphillips) [inline backend/apid/apid.go]: Should we make a copy for specifically for the GraphQL service? Otherwise we might be allowing it on the `apid`.

Comment (echlebek) [reply backend/apid/apid.go]: InsecureSkipVerify is only for clients.

Comment (palourde) [reply backend/apid/apid.go]: Good point, I applied `InsecureSkipVerify` to `tlsConfig` instead; I believe it only applies to client but I prefer to avoid any potential problem.

**Comment by nikkiki** [comment]
giphy

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,12 +7,13 @@ Versioning](http://semver.org/spec/v2.0.0.html).
...
 ## Unreleased
 
-### [5.0.0] - 2018-10-30
+### [5.0.0] - 2018-11-30
 
 ### Added
 - Add the `etcd-advertise-client-urls` config attribute to sensu-backend
 - Support for multiple API versions added to sensuctl create
 - Support for metadata added to wrapped resources (yaml, wrapped-json)
+- Added the backend configurationa attributes `api-listen-address` & `api-url`.
```
Comment (nikkiki) [inline CHANGELOG.md]:
```suggestion
- Added the backend configuration attributes `api-listen-address` & `api-url`.
```

**Comment by palourde** [comment]
This is me trying to fix multiple things at once

File: CHANGELOG.md [hunk 4]
```diff
@@ -34,6 +35,8 @@ uses the same facility as check subdue for handling time windows.
 - Metadata from wrappers and resources is now merged, with a preference given to
 the values coming from the wrapper. Labels and annotations are deep-merged.
 - Round-robin scheduling has been temporarily disabled.
+- The dashboard now uses the `api-url` configuration attribute to connect to the
```
Comment (nikkiki) [inline CHANGELOG.md]: Maybe add that `api-host` and `api-port` have been deprecated?

File: CHANGELOG.md [hunk 5]
```diff
@@ -53,6 +56,10 @@ period of disconnection from the backend.
 - Monitors are now properly namespaced in etcd.
 - Updating a users groups will no longer corrupt their password
 
+### Breaking Changes
+- The backend configuration attributes `api-host` & `api-port` have been
```
Comment (nikkiki) [inline CHANGELOG.md]: 💯

File: CHANGELOG.md (hunk 4 above)
Comment (echlebek) [inline CHANGELOG.md]: Should this say "no longer uses"?
