### PR TITLE
Replace uuid with event id in logging

### LINKED ISSUE #4093: event ID keys are not consistent in sensu-backend logs
## Expected Behavior

In reviewing sensu-backend logs, I can refer to a consistent key name for the event UUID.

## Current Behavior

sensu-backend log messages use inconsistent key names when logging event UUID. Some log messages use key `event_uuid`, whereas others use key `uuid`. 

## Possible Solution

Standardize name for key whose value is the event UUID

## Steps to Reproduce (for bugs)

1. Turn on debug level logging in your sensu-backend
2. Submit one or more events via the Agent, scheduled or using the agent's /events HTTP API
3. Identify UUID for the event, then grep the UUID from backend-logs
4. Note that although each message uses the same UUID value, the keys which provide that value vary

## Context

Some log messages use key `event_uuid`, whereas others use key `uuid`, and this appears to be inconsistent even for log messages coming from the same backend component but differing log levels:

```
{
  "check_name": "check-sensu-filebeat-process",
  "check_namespace": "monitoring",
  "component": "pipelined",
  "entity_name": "sd-25f8-415b",
  "entity_namespace": "monitoring",
  "handler": "monitoring-email",
  "level": "info",
  "msg": "sending event to handler",
  "time": "2020-11-05T09:30:00-05:00",
  "uuid": "47eedb71-9430-4120-b471-9680a1c2f09d"
}
{
  "assets": [
    "sensu-email-handler"
  ],
  "check": "check-sensu-filebeat-process",
  "component": "pipelined",
  "entity": "sd-25f8-415b",
  "event_uuid": "47eedb71-9430-4120-b471-9680a1c2f09d",
  "handler": "monitoring-email",
  "level": "debug",
  "msg": "fetching assets for handler",
  "namespace": "monitoring",
  "time": "2020-11-05T09:30:00-05:00"
}
```

Further more, the event payload sent to handlers and event-log (when configured) uses key name `id`.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

### PR DESCRIPTION
**Pull request by amdprophet**
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>

## What is this change?

Replaces all instances where `event_uuid` was logged with `event_id`.

## Why is this change necessary?

Closes #4093.

## Does your change need a Changelog entry?

Yes.

## Do you need clarification on anything?

Nope!

## Were there any complications while making this change?

Nope!

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No new documentation is required.

## How did you verify this change?

Just unit/integration tests.

## Is this change a patch?

No.

### CODE REVIEW

File: util/logging/logging.go [hunk 1]
```diff
@@ -14,9 +14,9 @@ func EventFields(event *types.Event, debug bool) map[string]interface{} {
 	}
 
 	fields := logrus.Fields{
+		"event_id":         event.ID,
 		"entity_name":      event.Entity.Name,
 		"entity_namespace": event.Entity.Namespace,
-		"uuid":             event.GetUUID().String(),
 	}
 
 	if event.HasCheck() {
```
Comment (ccressent) [inline util/logging/logging.go:22]: I'm not sure I 100% understand this: I thought only the field what supposed to
be renamed from "uuid" to "event_id". But here, the content of the field also
changes from event.GetUUID().String() to event.ID?

**Review by ccressent — COMMENTED** [review]
Nice work refactoring to use that `util/logging` package, I wasn't aware of it!
I don't believe we have good test coverage, if any, on the logging and the
fields it uses. So I'll ask: how confident are you this covers all the
relevant logs? This touches Events (obviously) and Handlers (less obvious).
Could there be other types (Mutators, Filters, ...) that could need a similar
treatment?

File: util/logging/logging.go (hunk 1 above)
Comment (ccressent) [inline util/logging/logging.go:22]: I'm not sure I 100% understand this: I thought only the field what supposed to
be renamed from "uuid" to "event_id". But here, the content of the field also
changes from `event.GetUUID().String()` to `event.ID`?

**Review by ccressent — COMMENTED** [review]
Nice work refactoring to use that `util/logging` package, I wasn't aware of it!
I don't believe we have good test coverage, if any, on the logging and the
fields it uses. So I'll ask: how confident are you this covers all the
relevant logs? This touches Events (obviously) and Handlers (less obvious).
Could there be other types (Mutators, Filters, ...) that could need a similar
treatment?

File: util/logging/logging.go (hunk 1 above)
Comment (amdprophet) [reply util/logging/logging.go:22]: I did a recursive search for `uuid` in the backend directory and went through the results to ensure the field was updated where it was being used.

@portertech @cwjohnston It's not clear if we only want to update the field name or not. Do we still want to use `event.GetUUID().String()`? or use `event.ID` for all `event_id` fields.

**Comment by amdprophet** [comment]
@ccressent updated & ready for review.

**Review by ccressent — APPROVED** [review]
