### PR TITLE
Split agent subscriptions properly in CLI flags

### LINKED ISSUE #2753: Entity subscriptions are stored incorrectly
## Expected Behavior
Entity subscriptions are an array of subscriptions that are specified on the agent, plus an extra entity subscription added by the server.

i.e.
```
["eenie", "meenie", "miney", "moe", "entity:tiger"]
```

## Current Behavior
```
["eenie,meenie,miney,moe", "entity:tiger"]
```
The array of subscriptions is always of length 2.

## Steps to Reproduce (for bugs)
```
sensuctl entity list --format json | jq .[0].subscriptions
```

## Context
Encountered while doing development work.

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

This commit fixes a bug where agents were sending the wrong
subscriptions in entities, as they would not be split properly
before being sent to the config.

Due to a quirk in how subscriptions are handled, this doesn't
affect any current scheduling mechanism. Nevertheless,
subscriptions must be properly stored in entities, especially for
future work that depends on entity details being correct.

## Why is this change necessary?

Closes #2753 

## Does your change need a Changelog entry?

Yes

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No doc changes required.

## How did you verify this change?

Manual verification.

### CODE REVIEW

File: agent/cmd/start.go [hunk 1]
```diff
@@ -170,8 +170,12 @@ func newStartCommand() *cobra.Command {
 			}
 
 			// Get a single or a list of subscriptions
-			subscriptions := viper.GetStringSlice(flagSubscriptions)
-			cfg.Subscriptions = subscriptions
+			subscriptions := viper.GetString(flagSubscriptions)
+			if subscriptions != "" {
+				cfg.Subscriptions = splitAndTrim(subscriptions)
+			} else {
+				cfg.Subscriptions = viper.GetStringSlice(flagSubscriptions)
```
Comment (palourde) [inline agent/cmd/start.go]: Maybe I'm missing something but I don't see how we could reach this condition without the `flagSubscriptions` flag being empty, and therefore subscriptions value at all.

Both `--subscriptions foo,bar` & `--subscriptions foo --subscriptions bar` will cause the _if_ statement to be true, and in the latter case the first value (foo) will be ignored. 

For reference, https://github.com/spf13/viper/issues/380.

Comment (echlebek) [reply agent/cmd/start.go]: I was just doing what you did :grin: 
https://github.com/sensu/sensu-go/blame/master/agent/cmd/start.go#L164

I'm not sure why it would drop the first value foo, but I think you're right about the if statement never being false.

Comment (palourde) [reply agent/cmd/start.go]: "Do what I say, don't do what I do" 🤣

Comment (palourde) [reply agent/cmd/start.go]: @echlebek Actually what I did worked because I set a slice as the default value, which will cause `viper.GetString` to return an empty value:

https://github.com/sensu/sensu-go/blob/master/agent/cmd/start.go#L238

Definitely not a clean solution though

Comment (echlebek) [reply agent/cmd/start.go]: OK. The subscriptions flag has a default value of an empty slice as well. I don't think we can support the canonical way to represent slices, (`--foo a --foo b`) as it would break the CLI... any suggestions?

Comment (palourde) [reply agent/cmd/start.go]: @echlebek Oh, we simply need to use `StringSlice` in pflag, I missed that. So we could simply do:

```
cfg.Subscriptions = viper.GetStringSlice(flagSubscriptions)

[...]

cmd.Flags().StringSlice(flagSubscriptions, viper.GetStringSlice(flagSubscriptions), "comma-delimited list of agent subscriptions")
```

Which would result in the following:

```
$ sensu-agent start --subscriptions foo
slice: [foo]
len: 1

$ sensu-agent start --subscriptions foo,bar
slice: [foo bar]
len: 2

$ sensu-agent start --subscriptions foo,bar --subscriptions qux
slice: [foo bar qux]
len: 3
```

Comment (echlebek) [reply agent/cmd/start.go]: Sounds like a plan, thanks!

**Comment by echlebek** [comment]
@palourde I've incorporated your suggestion and verified that it works. Thanks again!
