### PR TITLE
Omit substituted values command & check hook values

### LINKED ISSUE #2643: Dashboard shows redacted passwords in executed command section
## Expected Behavior
Configured redacted fields do not show values of those fields.

## Current Behavior
The Sensu Go Dashboard shows the executed command string, which is populated with redacted field values:

screen shot 2019-01-29 at 10 24 31 am

## Possible Solution
Ensure dashboard does not display sensitive values in plain text.

## Steps to Reproduce (for bugs)

1. Add agent configuration to `/etc/sensu/agent.xml`:
```
subscriptions: "echo_test"
redact: "my_test_pass,my_other_test_pass"
labels:
  my_test_pass: "secret1"
  my_other_test_pass: "secret2"
```
2. Add a simple check to use these values using `sensuctl create -f my_check.json`:
```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "collect-metrics",
    "namespace": "default"
  },
  "spec": {
    "command": "snmpget {{ .labels.my_test_pass }}",
    "interval": 10,
    "publish": true,
    "subscriptions": [
      "echo_test"
    ]
  }
}
```
3. Observer in Dashboard on Check Result screen, inside Check Summary that `secret1` is exposed.
4.

## Context
Security concerns for users of Sensu Go.

## Your Environment
Sensu Go 5.1.1 cli, agent and backend.

### PR DESCRIPTION
**Pull request by jamesdphillips**
## What is this change?

To guard against publishing sensitive/redacted client attribute values,
always use the original command and hook values.

Matches functionality in Sensu Classic, see [comment](https://github.com/sensu/sensu/blob/44f58ebdc6881161b34c67feaff572650d0b0ded/lib/sensu/client/process.rb#L172-L174) and [implementation](https://github.com/sensu/sensu/blob/44f58ebdc6881161b34c67feaff572650d0b0ded/lib/sensu/client/process.rb#L185-L186).

## Why is this change necessary?

Closes #2643 

## Does your change need a Changelog entry?

Yeah.

## Do you need clarification on anything?

Nada.

## Were there any complications while making this change?

Hubris.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No.

## Does this change require a new test case?

Maybe!

### CODE REVIEW

File: agent/check_handler_internal_test.go [hunk 1]
```diff
@@ -251,23 +252,21 @@ func TestHandleTokenSubstitutionNoKey(t *testing.T) {
...
+	entity.Labels = map[string]string{"foo": "bar"}
 	check := corev2.FixtureCheckConfig("check")
-	check.Interval = 0
-	assert.False(agent.prepareCheck(check))
-
-	// Valid check
-	check.Interval = 60
-	assert.True(agent.prepareCheck(check))
+	check.Command = "echo {{ .labels.foo }}"
+	prepareCheck(check, entity)
```
Comment (golangcibot) [inline agent/check_handler_internal_test.go]: Error return value of `prepareCheck` is not checked (from `errcheck`)
