### PR TITLE
InfluxDB Transformer Implementation

### LINKED ISSUE #1386: [Metric Extraction] Agent influxdb_line transformer
Child of https://github.com/sensu/sensu-go/issues/745
Depends on #1383 

Create a function `Transform(string) []MetricPoint, error` from the interface `Transformer` for influxdb_line. The function should accept a string (check output) and parse/transform the metrics to Sensu Metric Format. Return an error if the line is incorrectly formatted. The `influxdb_line` transformer will implement the [InfluxDB](https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/#measurement) line protocol, a single line of values, to extract the MetricPoints:

```
weather,location=us-midwest temperature=82 1465839830100400200
```

Additionally, add agent logic in check_handler.go to implement this transformer if the check’s `metric_format` matches the const `influxdb_line`.

### PR DESCRIPTION
**Pull request by nikkiattea**
Signed-off-by: Nikki Attea <nikki@sensu.io>

## What is this change?

Creates a transformer for InfluxDB Line protocol metrics. Allows the InfluxDB handler to parse a Sensu metric name for a tag field and measurement.

## Why is this change necessary?

Closes #1386.

## Does your change need a Changelog entry?

Yas.

## Do you need clarification on anything?

Nah.

## Were there any complications while making this change?

Nah.

### CODE REVIEW

File: agent/transformers/influx_db.go [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+			}
+			fieldList = append(fieldList, field)
+		}
+		i.FieldSet = fieldList
+
+		t, err := strconv.ParseInt(args[2], 10, 64)
+		if err != nil {
+			return InfluxList{}, errors.New("metric timestamp is invalid, third argument must be an int")
+		}
+		i.Timestamp = t
```
Comment (palourde) [inline agent/transformers/influx_db.go]: We should probably convert the influx timestamp, which uses nanosecond-precision, to a more standard 10 characters unix timestamp, so handlers know exactly what to expect. It seems we also did this in 1.x extensions: https://github.com/sensu/sensu-enterprise/blob/057f5af0d4960b70241fdf5181ce604d3afb4262/lib/sensu/enterprise/extensions/metric_parsers.rb#L143

File: agent/transformers/influx_db.go [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+// Influx contains values of influx db line metric format
+type Influx struct {
+	Measurement string
+	TagSet      []Tag
+	FieldSet    []Field
+	Timestamp   int64
+}
+
+// Tag is a key value pair representing an influxdb tag set
+type Tag struct {
```
Comment (palourde) [inline agent/transformers/influx_db.go]: We should probably call that `InfluxTag` or move that into a `transformers.go` file so it can shared across the transformers!

File: agent/transformers/influx_db.go [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+	Key   string
+	Value string
+}
+
+// Field is a key value pair representing an influxdb field set
+type Field struct {
```
Comment (palourde) [inline agent/transformers/influx_db.go]: Same as `Tag`

File: agent/transformers/influx_db.go (hunk 2 above)
Comment (palourde) [reply agent/transformers/influx_db.go]: I'm actually wondering if we couldn't use `[]*types.MetricTag{}` in `Influx` and simply avoid this struct? Thoughts?

Comment (nikkiattea) [reply agent/transformers/influx_db.go]: Yeah that probably eliminates some complexity if we use `MetricTag` instead!

File: agent/transformers/influx_db.go (hunk 3 above)
Comment (nikkiattea) [reply agent/transformers/influx_db.go]: Yeah, we could probably move this to a `transformers.go` file, I like that idea.

**Comment by nikkiattea** [comment]
Weird travis error for that failure, doesn't look like the cache is related here.
```
(98/98) Failed to write github.com/docker/docker@cbde00b44273a584bed2ee3513db68924b4a6dba
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/time: https://go.googlesource.com/time does not exist in the local cache and fetching failed: unable to get repository: Cloning into '/home/travis/gopath/pkg/dep/sources/https---go.googlesource.com-time'...
POST git-upload-pack (141 bytes)
error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502 Bad Gateway
fatal: The remote end hung up unexpectedly
: command failed: [git clone --recursive -v --progress https://go.googlesource.com/time /home/travis/gopath/pkg/dep/sources/https---go.googlesource.com-time]: exit status 128
```

**Comment by palourde** [comment]
@nikkiattea I canceled the AppVeyor because it was stuck on https://github.com/sensu/sensu-go/issues/1402. LGTM.
