### PR TITLE
Fix object listing in namespaces

### LINKED ISSUE #2371: Resources from similarly named namespaces are included in fetch results
## Expected Behavior

Fetch results from one namespace should not include results from another. 

## Current Behavior

* Given two namespaces `sensu` and `sensu-devel`.
* The query `GET /checks?namespace=sensu` returns checks not just from the `sensu` namespace but also `sensu-devel`.
* Caveat: Querying checks from the `sensu-devel` namespace does not include checks from the `sensu` namespace.

## Possible Solution

This is likely a prefix issue. We may likely simply need a trailing slash in the query to etcd.

## Steps to Reproduce (for bugs)

See above.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend
* Installation method (packages, binaries, docker etc.): docker
* Operating System and version (e.g. Ubuntu 14.04): macOS

### PR DESCRIPTION
**Pull request by ccressent**
## What is this change?
Resources from namespaces that share a common prefix, eg: "sensu" and
"sensu-devel", could be listed together.

This was due to a bug with key construction and key prefix usage in the
etcd client.

## Why is this change necessary?

Closes #2371.

## Does your change need a Changelog entry?

Yes, added.

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No.

### CODE REVIEW

File: backend/store/key_builder.go [hunk 1]
```diff
@@ -68,6 +81,7 @@ func (b KeyBuilder) BuildPrefix(keys ...string) string {
 		if key == "" {
 			continue
 		}
+		//
```
Comment (nikkiki) [inline backend/store/key_builder.go]:
```suggestion
```

Comment (ccressent) [reply backend/store/key_builder.go]: Whoops, left one of my "markers" for things to check out. Good catch!

**Comment by ccressent** [comment]
@nikkiki 
I think this covers it:
https://github.com/sensu/sensu-go/pull/2378/files#diff-7f3840639c3b6eb5237f3c0012451a08R29
