### PR TITLE
Bugfixes to curated namespaces

### LINKED ISSUE #3527: Curated namespaces do not work with a RoleBinding/ClusterRole combination

### PR DESCRIPTION
**Pull request by palourde**
## What is this change?

It fixes two bugs in the curated namespace functionality:

- A RoleBinding that refers to a ClusterRole should grant implicit access to its namespace
- A ClusterRoleBinding that refers to a ClusterRole, which grants access to  at least 1 namespaced resource, should grant access to all namespaces

## Why is this change necessary?

Closes #3527

## Does your change need a Changelog entry?

Added

## Do you need clarification on anything?

Nope

## Were there any complications while making this change?

Curated namespaces are hard! 😅 

## Have you reviewed and updated the documentation for this change? Is new documentation required?

Nope

## How did you verify this change?

Unit tests

## Is this change a patch?

Yep

### CODE REVIEW

File: backend/api/namespace.go [hunk 1]
```diff
@@ -127,6 +116,29 @@ func (a *NamespaceClient) ListNamespaces(ctx context.Context) ([]*corev2.Namespa
...
+			return true
+		}
+
+		// Determine if this ClusterRoleBinding provides implicit access to
+		// namespaced resources
+		if binding.GetObjectMeta().Namespace == "" {
+			for _, resource := range rule.Resources {
+				if stringsutil.InArray(resource, corev2.CommonCoreResources) {
+					// All resources of type "namespace" are allowed
+					logger.Debugf("all namespaces implicitely authorized by the binding %s", binding.GetObjectMeta().Name)
```
Comment (jamesdphillips) [inline backend/api/namespace.go]: at the risk of being a pedant... `s/implicitely/implicitly/g`

Comment (palourde) [reply backend/api/namespace.go]: Good catch! 😅
