### PR TITLE
Fix a deadlock in the agent

### LINKED ISSUE #2367: Agent reconnection to backend Issue
## Expected Behavior
When the backend nodes are back to be reachable by sensu agent. It must be able to work back normaly and run check like a charm.

## Current Behavior
Context : Working on AWS plateform
Backend are reachable by our agents through an ALB AWS (Application Load Balancer)
To improve our Sensu Proof Of Concept plateform and improve our knowledge on sensu fonctionnality to block the traffic between our Agent and the Backend Node. 

So we delete the port 8081 from our Security Group which make backend nodes unreachable for our sensu agent as you can see : 
**Nov 20 14:46:43 techops-52059 sensu-agent[26482]: {"component":"agent","error":"Connection error: websocket: close 1006 (abnormal closure): unexpected EOF","level":"error","msg":"transport receive error","time":"2018-11-20T14:46:43+01:00"}
Nov 20 14:46:53 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:46:53+01:00"}
Nov 20 14:47:13 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:47:13+01:00"}
Nov 20 14:47:33 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:47:33+01:00"}
Nov 20 14:47:53 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:47:53+01:00"}
Nov 20 14:48:13 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:48:13+01:00"}
Nov 20 14:48:33 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:48:33+01:00"}
Nov 20 14:48:53 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:48:53+01:00"}
Nov 20 14:49:13 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:49:13+01:00"}
Nov 20 14:49:33 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:49:33+01:00"}
Nov 20 14:49:53 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:49:53+01:00"}
Nov 20 14:50:13 techops-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:50:13+01:00"}
Nov 20 14:50:58 techops-52059 sensu-agent[26482]: {"component":"agent","error":"dial tcp ALB-IP:8081: connect: connection timed out","level":"error","msg":"reconnection attempt failed","time":"2018-11-20T14:50:58+01:00"}**

During the outage the netstat display this before reach the "Connection Timed out " :
 **root@tech-52059 >netstat -lapunte |grep sensu
tcp        0      0 127.0.0.1:3030          0.0.0.0:*               LISTEN      998        10005644    26482/sensu-agent
tcp        0      0 127.0.0.1:3031          0.0.0.0:*               LISTEN      998        10004749    26482/sensu-agent
tcp        0      1  X.X.X.X:43610          ALB-IP:8081     SYN_SENT    998        10007611    26482/sensu-agent
udp        0      0 127.0.0.1:3030          0.0.0.0:*                           998        10005643    26482/sensu-agent
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           998        10005645    26482/sensu-agent**

Once Timed out reached : 
**root@tech-52059 >netstat -lapunte |grep sensu
tcp        0      0 127.0.0.1:3030          0.0.0.0:*               LISTEN      998        10005644    26482/sensu-agent
tcp        0      0 127.0.0.1:3031          0.0.0.0:*               LISTEN      998        10004749    26482/sensu-agent
tcp        1      0 X.X.X.X:43610      ALB-IP:8081     CLOSE_WAIT  998        10007611    26482/sensu-agent
udp        0      0 127.0.0.1:3030          0.0.0.0:*                           998        10005643    26482/sensu-agent
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           998        10005645    26482/sensu-agent**

I recover the Security Group setup and add the port 8081, agent are now reaching sensu backend and we are back in a nominal situation .. Normaly  :smiling_imp: 
Logs on agent side : 
**Nov 20 14:50:58 tech-52059 sensu-agent[26482]: {"component":"agent","error":"dial tcp ALB-IP:8081: connect: connection timed out","level":"error","msg":"reconnection attempt failed","time":"2018-11-20T14:50:58+01:00"}
Nov 20 14:52:01 tech-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"successfully connected","time":"2018-11-20T14:52:01+01:00"}
Nov 20 14:52:01 tech-52059 sensu-agent[26482]: {"component":"agent","level":"info","msg":"sending keepalive","time":"2018-11-20T14:52:01+01:00"}**

Logs on Backend side : 
**Nov 20 13:51:52 BACKEND-NODE sensu-backend[757]: {"check":"check-ntp-time","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-11-20T13:51:52Z","topic":"sensu::check:techops:ubuntu"}
Nov 20 13:52:01 ip-10-107-122-171 sensu-backend[757]: {"addr":"ALB-IP:60454","component":"agentd","id":"tech-52059","level":"info","msg":"agent connected","subscriptions":["ubuntu","front","entity:tech-front-52059"],"time":"2018-11-20T13:52:01Z"}
Nov 20 13:52:01 ip-10-107-122-171 sensu-backend[757]: {"component":"agentd","level":"debug","msg":"subscribing to topic","time":"2018-11-20T13:52:01Z","topic":"sensu::check:techops:ubuntu"}
Nov 20 13:52:01 ip-10-107-122-171 sensu-backend[757]: {"component":"agentd","level":"debug","msg":"subscribing to topic","time":"2018-11-20T13:52:01Z","topic":"sensu::check:techops:front"}
Nov 20 13:52:01 ip-10-107-122-171 sensu-backend[757]: {"component":"agentd","level":"debug","msg":"subscribing to topic","time":"2018-11-20T13:52:01Z","topic":"sensu::check:techops:entity:tech-front-52059"}
Nov 20 13:52:11 ip-10-107-122-171 sensu-backend[757]: {"addr":"ALB-IP:60454","component":"agentd","id":"tech-52059","level":"warning","msg":"stopping session","recv error":"Connection error: websocket: close 1006 (abnormal closure): unexpected EOF","time":"2018-11-20T13:52:11Z"}**

As you can see the Backend Stopping the session => Connection Error Websocket
The agent didn't log anymore and looks like stucked no one check is performed etc.. the Netstat command return this : 
**netstat -lapunte |grep sensu
tcp        0      0 127.0.0.1:3030          0.0.0.0:*               LISTEN      998        10005644    26482/sensu-agent
tcp        0      0 127.0.0.1:3031          0.0.0.0:*               LISTEN      998        10004749    26482/sensu-agent
tcp        1      0 X.X.X.X:43610      ALB-IP:8081     CLOSE_WAIT  998        10007611    26482/sensu-agent
udp        0      0 127.0.0.1:3030          0.0.0.0:*                           998        10005643    26482/sensu-agent
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           998        10005645    26482/sensu-agent**

only the restart of all our sensu agents fix the problem : 

**root@tech-52059 >service sensu-agent restart
[ ~ ]
root@tech-52059 >netstat -lapunte |grep sensu
tcp        0      0 127.0.0.1:3030          0.0.0.0:*               LISTEN      998        10039039    28856/sensu-agent
tcp        0      0 127.0.0.1:3031          0.0.0.0:*               LISTEN      998        10039416    28856/sensu-agent
tcp        0      0 X.X.X.X:44950      ALB-IP:8081     ESTABLISHED 998        10039421    28856/sensu-agent
udp        0      0 127.0.0.1:3030          0.0.0.0:*                           998        10039038    28856/sensu-agent
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           998        10039040    28856/sensu-agent**

Looks like a poor TCP session management on sensu or a websocket depencies ?

Something goes wrong between sensu agent and sensu backend during a network interruption, I've done a tcpdump during my test and when the agent reconnected to the backend a GET request is send with following details : 
**Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
    Host: internal-poc-sensu-alb.eu-west-1.elb.amazonaws.com:8081\r\n
    User-Agent: Go-http-client/1.1\r\n
    Authorization: Basic XXXXX\r\n
        Credentials: XXXX:XXXXX
    Connection: Upgrade\r\n
    Sec-WebSocket-Key: 0HpTiocDydA1b+XpCIdg4w==\r\n
    Sec-WebSocket-Version: 13\r\n
    Sensu-Agentname: XXXXXXXXXX \r\n
    Sensu-Namespace: techops\r\n
    Sensu-Subscriptions: ubuntu,front\r\n
    Sensu-User: agent\r\n
    Upgrade: websocket\r\n
    \r\n
    [Full request URI: http://internal-poc-sensu-alb.eu-west-1.elb.amazonaws.com:8081/]**

## Possible Solution
No one idea about possible solution, I don't know how is working the layer WebSocket between sensu agent and sensu backend.

## Steps to Reproduce (for bugs)
1) be sure Agent sensu is running and working properly
2) make sensu agent unavailable to reach sensu backend
3) check logs on agent side
4) restore the link between sensu agent and sensu backend
5) check logs => agent connected to backend
6) Agent stopping work but running and TCP CLOSED.

## Context
This issue can be problematic in case of network outage , the agent should be able to reconnect properly to the backend and rerun check.

## Your Environment
* Sensu version used : 
sensu-agent version 2.0.0-beta.8-8#c07579c, build c07579c0b20f5f5e12788fb0704c3a9138882b58, built 2018-11-15T18:16:07+0000

* Installation method : Following documentation installation of sensu.io
* Operating System and version : Ubuntu 18.04

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

This commit fixes a bug in the agent where the send queue could
fill up with keepalives after a long period of disconnection. On
successful reconnection, the agent would try to send an immediate
keepalive, before returning control to the event loop responsible
for normal operation. This operation would block forever, resulting
in deadlock.

Agents will now only buffer a single keepalive; when the agent
reconnects, instead of sending multiple keepalives, it will send
only one, regardless of how much time has progressed.

This commit also fixes a bug in the retry library, where the
MaxDelayInterval parameter was not considered in computing the
amount of time to wait before retrying.

Finally, the agent's retry timeout has been adjusted. The agent
will retry on the following schedule:

10 ms, 100 ms, 1s, 10s

After reaching 10s, the agent will wait a maximum of 10s (with
jitter) before retrying.

## Why is this change necessary?

Closes #2367 

## Does your change need a Changelog entry?

Yes

## Do you need clarification on anything?

No

## Were there any complications while making this change?

I noticed that the retry library had a slight defect, which I corrected.

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -27,6 +27,8 @@ import (
 	"github.com/sirupsen/logrus"
 )
 
+const sendQueueTimeout = time.Second
```
Comment (golangcibot) [inline agent/agent.go]: `sendQueueTimeout` is unused

**Comment by grepory** [comment]
I have been thinking about the keep alive issue. We shouldn’t keep the sendPeriodicKeepalives goroutine around.

We should stop trying to send keepalives after we disconnect. Instead manage it in the send loop for the connection with a timer channel added to the select there.

There’s another problem with the send queue as well. When something is pushed to the API, statsd listener, or socket listener, an event will be written to the sendq—blocking the sendq further. We should remove the call to sendKeepalive in the connection manager and allow the receiveLoop and sendLoops to start.

**Comment by echlebek** [comment]
I was going to do that, but I didn't want to disrupt the intended logic. That's why I added the keepalives channel, in order to keep from blocking on the sendKeepalive function.

Removing the call after reconnecting would solve the problem as well though. I'll make the change.

**Comment by echlebek** [comment]
Actually, thinking about it some more, we don't want to fill up the sendq with keepalives either. There's just no reason to ever have more than a single keepalive queued up.

**Comment by grepory** [comment]
That’s why I don’t want keepalives in the sendq. Instead just send them directly from the send loop in the select block there.

We also don’t want to queue keepalives _ever_. The entity’s last seen field is based on keepalive timestamp. So we want the _latest_ keepalive. If you send keepalives with a timer directly from the sendloop it has that effect. 

The intended logic is wrong. ^_^

File: agent/agent.go [hunk 2]
```diff
@@ -249,19 +204,14 @@ func (a *Agent) connectionManager() {
...
-		if err := a.sendKeepalive(); err != nil {
-			logger.WithError(err).Error("error sending keepalive")
-		}
-
 		done := make(chan struct{})
 
-		go receiveLoop(conn, a.handler, done)
-		sendLoop(conn, a.sendq, done, a.stopping)
+		go a.receiveLoop(conn, done)
+		a.sendLoop(conn, done)
```
Comment (ccressent) [inline agent/agent.go]: I love that now `send()` and `recv()` are "symmetric", as they should!
