### PR TITLE
[Web UI] Remove re-run keepalives on Events and Checks List

### LINKED ISSUE #2410: [Web UI] Error: GraphQL error: Abstract type Error must resolve to an Object type at runtime for field ExecuteCheckPayload.errors with value "{ERR_NOT_FOUND id not found}", received "<nil>".
Error on the WebGUI when attempting to re-run checks.

Issue happens on a fresh installation where the back-end and a single agent were just brought online. No further checks defined (so only keepalive available)

## Expected Behavior
WebGUI not crashing

## Current Behavior

WebGUI crashing with the error tracedata below

## Steps to Reproduce (for bugs)

1.Installation of sensu-backend and sensu-agent on the same host with cent os 7 using yum packages as described in the installation manuals (I hope...)
2.configuration using sensuctl
3.launch webgui, landing on the event view
4.see one event of one entity ("keepalive" of the host, of course...) 
5.attempt "re-run check" on the event
image

6!!!! crash happens!!!!
image

## Context

**Web UI Stack Trace:**

at `ApolloError` (/static/js/main.566beacb.js:7)
at `next` (/static/js/main.566beacb.js:60)
at `notifySubscription` (/static/js/main.566beacb.js:60)
at `onNotify` (/static/js/main.566beacb.js:60)
at `next` (/static/js/main.566beacb.js:60)
at `notifySubscription` (/static/js/main.566beacb.js:60)
at `onNotify` (/static/js/main.566beacb.js:60)
at `next` (/static/js/main.566beacb.js:60)
at `next/</<` (/static/js/main.566beacb.js:66)
at `next/<` (/static/js/main.566beacb.js:66)
at `next` (/static/js/main.566beacb.js:66)
at `notifySubscription` (/static/js/main.566beacb.js:60)
at `onNotify` (/static/js/main.566beacb.js:60)
at `next` (/static/js/main.566beacb.js:60)
at `batchHandler/</<` (/static/js/main.566beacb.js:66)

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `c07579c`
* Installation method (packages, binaries, docker etc.): yum packages
* Operating System and version (e.g. Ubuntu 14.04): cent os 7

### PR DESCRIPTION
**Pull request by dabria**
## What is this change?
Closes #2410
Removes the ability to re-run keepalives from the events and checks list

## Why is this change necessary?
We don't have a way to do this at this point in time, so it causes an exception in the frontend.

## Does your change need a Changelog entry?
Added one

## Were there any complications while making this change?
Disabling the button instead of not rendering it solves this ~There's some weirdness if you are doing bulk actions, the list header icon for re-run is removed if you add a keepalive to the selected items. However, if you unselect that keepalive the re-run button does not return unless you deselect the whole list. I'm open to suggestions on how to correct this.~

### CODE REVIEW

File: dashboard/src/components/partials/EventsList/EventsListItem.js [hunk 1]
```diff
@@ -140,13 +142,13 @@ class EventListItem extends React.Component {
...
             </ToolbarMenu.Item>
-            <ToolbarMenu.Item id="re-run" visible="never">
+            <ToolbarMenu.Item id="unsilence" visible="never">
               <UnsilenceMenuItem
                 disabled={!event.isSilenced}
                 onClick={this.props.onClickClearSilences}
               />
             </ToolbarMenu.Item>
-            <ToolbarMenu.Item id="re-run" visible="never">
+            <ToolbarMenu.Item id="delete" visible="never">
```
Comment (jamesdphillips) [inline dashboard/src/components/partials/EventsList/EventsListItem.js]: oof- good catch.

File: dashboard/src/components/partials/EventsList/EventsListHeader.js [hunk 2]
```diff
@@ -112,6 +112,9 @@ class EventsListHeader extends React.Component {
 
     const allSelectedSilenced = selectedSilenced.length === selectedCount;
     const allSelectedUnsilenced = selectedSilenced.length === 0;
+    const selectedKeepalives = selectedItems.filter(
+      ev => ev.check.name === "keepalive",
+    );
```
Comment (jamesdphillips) [inline dashboard/src/components/partials/EventsList/EventsListHeader.js]: 👍
