### PR TITLE
Better TLS support for sensuctl

### LINKED ISSUE #2541: Proper TLS support in sensuctl
`sensuctl` support for TLS is close to non-existent.

Unless the backend is using a certificate signed by a "proper" authority installed system-wide it's impossible to connect to the API over HTTPS.

On Windows systems, `sensuctl` cannot work over HTTPS at all because there is no mechanism in Go's x509 library to load the "default", system-wide CA certificates (see [here](https://golang.org/src/crypto/x509/cert_pool.go?s=1328:1368#L45)).

## Expected Behavior

`sensuctl` should be able to talk to the API over HTTPS, in many different
scenarios:

- ability to provide my own CA certificates if needed
- ability to skip certificate verification (probably with a warning)
- ability to provide a client certificate if asked by the server
- ...

## Current Behavior

Unless one is using a non-windows system and doctors the system-wide CA certificates (or use a certificate that's signed by a "proper" authority), it's impossible to talk to the API over HTTPS.

## Context

I was working on #2300, making small improvements to some aspects of our use of TLS and attempted to address @cwjohnston's comment about `sensuctl` while I was at it.

### LINKED ISSUE #2575: Unable to use self-signed certs with backend
## Expected Behavior

I'd expect a self-signed certificate to work.

## Current Behavior

```
[root@sensu-backend ~]# sensuctl configure -n --url 'https://localhost:8080' --username 'admin' --password 'P@ssw0rd!'

Error: unable to authenticate with error: Get https://localhost:8080/auth: x509: certificate signed by unknown authority
```

## Steps to Reproduce (for bugs)

Generate CA and cert:
```
 openssl req -newkey rsa:2048 -nodes -keyout /etc/sensu/ca_key.pem -x509 -days 365 -out /etc/sensu/ca.pem -subj '/CN=localhost'
openssl req -newkey rsa:2048 -nodes -keyout /etc/sensu/key.pem -out /etc/sensu/localhost.csr -subj '/CN=localhost'
openssl x509 -req -in /etc/sensu/localhost.csr -CA /etc/sensu/ca.pem -CAkey /etc/sensu/ca_key.pem -CAcreateserial -out /etc/sensu/cert.pem -days 365 -sha256
```
Configure backend:
```yaml
---
state-dir: "/var/lib/sensu/sensu-backend"
cert-file: "/etc/sensu/cert.pem"
key-file: "/etc/sensu/key.pem"
trusted-ca-file: "/etc/sensu/ca.pem"
insecure-skip-tls-verify: true
```

Try to run `sensuctl configure`:

```
[root@sensu-backend ~]# sensuctl configure -n --url 'https://localhost:8080' --username 'admin' --password 'P@ssw0rd!'

Error: unable to authenticate with error: Get https://localhost:8080/auth: x509: certificate signed by unknown authority
```

## Context

Working on better support for SSL with sensu-puppet module and am having trouble testing SSL to verify the module fully supports SSL enabled configurations.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.0
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

### PR DESCRIPTION
**Pull request by ccressent**
## What is this change?

Add support for the following TLS related options to `sensuctl`:
- `--trusted-ca-file`
- `--insecure-skip-tls-verify`
- `--cert-file`
- `--key-file`

These have the same meaning as their counterparts in `sensu-backend` and `sensu-agent`.

## Why is this change necessary?

Closes #2541.
Closes #2575.

## Does your change need a Changelog entry?

Yes, added.   

## Have you reviewed and updated the documentation for this change? Is new documentation required?

The documentation needs to be updated to reflect the new options.
**I haven't done that yet.**

## Does this change require a new test case?

A few tests for various TLS configurations can be added to the QA checklist.
**I haven't done that yet.**

### CODE REVIEW

**Comment by treydock** [comment]
What would be a supported way to make sensuctl always use the `--trusted-ca-file` flag without aliases or specifying it always at command line?  For Puppet module for sensu it would be handy if passing `--trusted-ca-file` with `sensuctl configure` would update the JSON config for sensuctl so that all future executions would use the CA file.  I don't know if it would be better to alternatively create a subcommand like `sensuctl config set-trusted-ca-file [path]`.

If go with `sensuctl configure` approach it would have to update the JSON as well as use the CA for communications in order to support bootstrapping.

**Comment by treydock** [comment]
Also modifying the JSON isn't working:

```
[root@sensu-backend ~]# cat /root/.config/sensu/sensuctl/cluster
{
  "api-url": "https://sensu-backend.example.com:8080",
  "edition": "core",
  "trusted-ca-file": "/etc/sensu/ssl/ca.crt",
  "cert-file": "",
  "key-file": "",
  "insecure-skip-tls-verify": false,
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDg2MjI0MTUsImp0aSI6ImIzMmY0MDc3NWVjYjlkNjUxYTFiZjI0OWMyYmM3MmIyIiwic3ViIjoiYWRtaW4iLCJncm91cHMiOlsiY2x1c3Rlci1hZG1pbnMiLCJzeXN0ZW06dXNlcnMiXSwicHJvdmlkZXIiOnsicHJvdmlkZXJfaWQiOiJiYXNpYy9kZWZhdWx0IiwidXNlcl9pZCI6ImFkbWluIn19.mhzDGKRZDjgxJJ5T0wfKnoKjbpRIUO9cwX3Kv5rIgF4",
  "expires_at": 1548622415,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjNGNiNTQ3YTFmNWUwMmE4MDFhNjgyM2ZlYTkxNWJkNCIsInN1YiI6ImFkbWluIiwiZ3JvdXBzIjpudWxsLCJwcm92aWRlciI6eyJwcm92aWRlcl9pZCI6IiIsInVzZXJfaWQiOiIifX0.bAIdIQDrokaO0KloOD6-Wcb_KEPXVOzQol0F0DGaSNE"
}
[root@sensu-backend ~]# sensuctl entity list
Error: failed to request new refresh token; client returned 'Post https://sensu-backend.example.com:8080/auth/token: x509: certificate signed by unknown authority'
[root@sensu-backend ~]#
```

It only works if I specify at command line:

```
[root@sensu-backend ~]# sensuctl entity list --trusted-ca-file /etc/sensu/ssl/ca.crt
             ID               Class    OS              Subscriptions                       Last Seen
 ─────────────────────────── ─────── ─────── ────────────────────────────────── ───────────────────────────────
  el7-agent.example.com       agent   linux   entity:el7-agent.example.com       2019-01-26 18:11:37 +0000 UTC
  sensu-backend.example.com   agent   linux   entity:sensu-backend.example.com   2019-01-27 21:03:16 +0000 UTC
```

**Comment by echlebek** [comment]
@treydock looking at this again, it seems that the PR does support persisting this config. Are you sure that your CA cert is working with `--trusted-ca-file` and not with JSON config?

**Comment by treydock** [comment]
Being able to specify the trusted CA is enough to close out #2575.  I have verified that is enough to use certificates not trusted by the system which should be enough to support self-signed certificates as long as there is a CA certificate.

I am certain the flags worked and not the config.  When I used the flags the config had an empty string for `trusted-ca-file`.  I ran with the flag before and after changing the JSON so I know the flag worked without updates to the JSON.  I can re-run my tests later today to be doubly sure but if I recall correctly I was only able to get the CA to work with command line arguments.

**Comment by echlebek** [comment]
@treydock OK thanks, I will look into it!

**Comment by treydock** [comment]
Don't know if it helps at all but I do recall that all the new flags got automatically added to the config JSON but testing showed they had no impact on sensuctl execution.

File: cli/client/config/basic/basic.go [hunk 1]
```diff
@@ -92,6 +94,14 @@ func (c *Config) flags(flags *pflag.FlagSet) {
 	if value, err := flags.GetString("api-url"); err == nil && value != "" {
 		c.Cluster.APIUrl = value
 	}
+
+	if value, err := flags.GetBool("insecure-skip-tls-verify"); err == nil && value != false {
```
Comment (golangcibot) [inline cli/client/config/basic/basic.go]: should omit comparison to bool constant, can be simplified to value (from `gosimple`)

**Comment by echlebek** [comment]
@treydock I found that the command line flags were overriding the cluster config, using default values even if the flags weren't set. It should work as you expect now.

**Comment by ccressent** [comment]
@echlebek: you are correct, `--cert-file` and `--key-file` on the client are useless right now because the backend never asks for the client's certificate. I had added them to the client in preparation of #2548, while I was touching nearby code anyway. I'm totally OK with removing those options for now, as you did; we can re-add that code later when needed!

@treydock: sorry I messed up the persistence in the configuration file...

**Comment by gbolo** [comment]
@ccressent @echlebek @palourde please see #2709 which is related to this PR
