### PR TITLE
Separate system info collection from getAgentEntity()

### LINKED ISSUE #1947: Separate system info collection from getAgentEntity()
## Expected Behavior
The collection of system info should not affect an agent's ability to send keepalives.

## Current Behavior
It is possible for system info collection to take up to 3 seconds, or outright fail, which has a direct effect on how long a keepalive takes to send or whether it is sent at all.

## Possible Solution
Move system info collection into a new goroutine that starts up with an agent that will cache the latest fetched system info. Update `getAgentEntity()` to retrieve system info from the cache.

The asset manager will also need to be updated to retrieve system info from this cache but should be handled under another issue.

### PR DESCRIPTION
**Pull request by ccressent**
## What is this change?

Instead of `agent.getAgentEntity()` being responsible for gathering system info, the agent itself now spawns a goroutine responsible for periodically updating a local cache of system info.

`agent.getAgentEntity()` now reads that cache whenever it needs to retrieve system information.

## Why is this change necessary?

Closes #1947.
Might help #1829. 

## Does your change need a Changelog entry?

Yes, added as part of of the change.

## Do you need clarification on anything?

- Initial keepalive message might not have system info. That doesn't change how
  it used to work, but is that OK?
- Unsure how/if I should add tests for the change. It might lead to some refactoring?
- Any potential impact I might be missing? Would you have done it differently?
  
## Were there any complications while making this change?

- `lsb_release` needed for some distros to pass tests in `system` package (eg:
  Arch). I'll open a separate issue for which the "fix" would probably simply be
  an update to the README.
- unsure about testing (reproducing #1947 easily, need for test in the first
  place, ease of testing without needlessly refactoring)
  
## Have you reviewed and updated the documentation for this change? Is new documentation required?

Nothing relevant to change that I could find in the "Sensu Core" doc set for
v2.0.

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -404,6 +428,21 @@ func (a *Agent) Run() error {
 		logger.WithError(err).Error("error sending keepalive")
 	}
 
+	go func() {
+		// TODO(cyril): create a separate config knob for system info refresh interval?
```
Comment (mercul3s) [inline agent/agent.go]: Would this be a user-configurable agent config attribute, or a default based on the keepalive value (as it is now)?

Comment (ccressent) [reply agent/agent.go]: I'm assuming there is little value for the user to be able to configure it, except maybe in extreme edge cases such as the user "needing" to change/reconfigure network interfaces more frequently than the system information is refreshed?

I would be happy with a default value of our choosing, say `DefaultSystemInfoRefreshInterval = 60`, that wouldn't be exposed in the user config:
- we can change it at will at compile time
- if it really becomes a valid need for users we can then expose it

**Comment by ccressent** [comment]
@echlebek: I'm also all for testing! It sounds like the we have quite a bit of refactoring and additional testing to do on that `agent` package. I agree, let's make that work part of a future tech debt task then.

@amdprophet: that sounds like another valid approach, but I don't have enough high level understanding of the system yet to make a choice here. I made that choice based on the expected behavior described in #1947 ("The collection of system info should not affect an agent's ability to send keepalives.") and a quick read of #1829. I'm happy to revisit later if the current choice proves to not be the best!

**Comment by grepory** [comment]
Definitely block on sending the first keepalive until we have system info.
