### PR TITLE
Use package liveness in keepalived

### LINKED ISSUE #2530: Keepalive events will stop occurring on backend restart
Although PR #2502 fixes the problems with Check TTL and Keepalives in the common case, the solution is in-memory only, and will fail when the backend's state is refreshed (i.e., restarted).

While monitors can transition between backends via etcd, the failure loop that causes backends to emit events relies on in-memory state.

This is related to #2135 and users who rely on durable keepalive and check TTL failure behaviour should be aware of this.

### LINKED ISSUE #2622: Keepalives conflict with entity deregistration
## Expected Behavior
Deregisterer entities should not experience keepalive failure events, and should not be listed as entities after they have deregistered.

## Current Behavior
Entities can appear after deregistration.

## Context
Reported by pfak in the community slack.

### PR DESCRIPTION
**Pull request by echlebek**
## What is this change?

This commit makes use of package liveness in keepalived, in order
to achieve durable keepalives. With this change applied, failing
keepalives will continue firing even if one or more backends is
lost. (Assuming etcd quorum is intact)

## Why is this change necessary?

Closes #2530 
Closes #2622 

## Does your change need a Changelog entry?

Yes

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -173,6 +173,9 @@ func (a *Agent) Run() error {
 	if err := v2.ValidateName(a.config.AgentName); err != nil {
 		return fmt.Errorf("invalid agent name: %v", err)
 	}
+	if timeout := a.config.KeepaliveTimeout; timeout > 0 && timeout < 5 {
```
Comment (nikkiki) [inline agent/agent.go]: Can a KeepaliveTimeout be 0 seconds? That would essentially disable failing keepalives right?

Comment (echlebek) [reply agent/agent.go]: The minimum value is 5 seconds, and we don't support disabling keepalives currently.

File: backend/keepalived/keepalived.go [hunk 2]
```diff
@@ -298,54 +304,114 @@ func createRegistrationEvent(entity *types.Entity) *types.Event {
...
-	entity.LastSeen = e.Timestamp
+	lager = lager.WithFields(logrus.Fields{"entity": name, "namespace": namespace})
+	lager.Info("entity is alive")
+}
 
-	if err := k.store.UpdateEntity(ctx, entity); err != nil {
-		logger.WithError(err).Error("error updating entity in store")
-		return err
+func (k *Keepalived) dead(key string, prev liveness.State, leader bool) {
+	lager := logger.WithFields(logrus.Fields{
```
Comment (nikkiki) [inline backend/keepalived/keepalived.go]: I propose we change _all_ instances of `logger` to `lager` 🍻

File: agent/agent.go (hunk 1 above)
Comment (echlebek) [reply agent/agent.go]: After chatting with Nikki I realized that the condition should only check for `timeout < 5`

File: backend/keepalived/keepalived.go (hunk 2 above)
Comment (echlebek) [reply backend/keepalived/keepalived.go]: But then my strategy for not overriding the logger variable would break :)

Comment (nikkiki) [reply backend/keepalived/keepalived.go]: giphy

File: backend/keepalived/integration_test.go [hunk 3]
```diff
@@ -55,23 +60,36 @@ func TestKeepaliveMonitor(t *testing.T) {
...
+		},
 		Entity:    entity,
 		Timestamp: time.Now().Unix(),
 	}
 
+	if err := store.UpdateEvent(ctx, keepalive); err != nil {
+		t.Fatal(err)
+	}
+
+	factory := liveness.EtcdFactory(context.Background(), client)
```
Comment (nikkiki) [inline backend/keepalived/integration_test.go]: Can we use the same context that the store uses on L52, or is there another reason we have independent contexts?

Comment (echlebek) [reply backend/keepalived/integration_test.go]: That context carries extra information, and since it's being created by a function call in another package, I'd prefer to keep them separate.

Comment (nikkiki) [reply backend/keepalived/integration_test.go]: That makes sense, was just curious!
